config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root to: "exams#new", as: "authenticated_root"
  end
  unauthenticated do
    root "static_pages#home"
  end

  devise_for :users

  resources :users, only: :show

  resources :exams, except: [:index, :destroy]
  namespace :admin do
    root "users#index"
    resources :imports, only: :create
    resources :users, except: [:show]
    resources :categories do
      resources :questions
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :exams, dependent: :destroy
  has_many :questions, dependent: :destroy

  validates :name, presence: true
  validates :max_time, presence: true, numericality: {only_integer: true,
    greater_than: 0}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @categories = Category.page params[:page]
  end

  def show
    @questions = @category.questions
  end

  def new
  end

  def create
    if @category.save
      redirect_to admin_categories_url,
        success: t("messages.admin.categories.created")
    else
      reder :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      redirect_to admin_category_url,
        success: t("messages.admin.categories.updated")
    else
      render :edit
    end
  end

  def destroy
    flash = if @category.destroy
      {success: t("messages.admin.categories.deleted")}
    else
      {danger: t("messages.admin.categories.not_deleted")}
    end
    redirect_to admin_categories_url, flash
  end

  private
  def category_params
    params.require(:category).permit :name, :max_time
  end
end

app/views/admin/categories/_category.html.erb
<aside>
  <section class="user_info">
    <h1>
      <%= link_to category.name, [:admin, category] %>
      <%= link_to "", admin_category_path(category), method: :delete, data: {confirm: 
        t(".confirm_sure")}, class: "glyphicon glyphicon-trash" %>
    </h1>
    <p>
      <%= t ".created_time", created_time: category.created_at %>
    </p>
    <p>
      <%= t ".updated_time", updated_time: category.updated_at %>
    </p>
  </section>
</aside>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :max_time %>
  <%= f.number_field :max_time, class: "form-control" %>

  <%= f.submit t(".submit"), class: "btn btn-primary" %>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render partial: "form" %>  
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, t(".title") %>

<h1><%= t ".title" %></h1>
<%= link_to t(".add"), new_admin_category_path %>
<ul class="users">
  <%= render @categories %>
</ul>
<%= paginate @categories %>

app/views/admin/categories/show.html.erb
<% provide :title, @category.name %>
<div class="row">
  <aside class="col-md-6">
    <section class="user_info">
      <h1>
        <%= @category.name %>
      </h1>
      <p>
        <%= t ".max_time", max_time: @category.max_time %>
      </p>
      </br>
      <h3>
        <%= link_to t(".add_quesion"), [:new, :admin, @category, :question] %>
      </h3>
      <h3>
        <%= link_to t("edit"), [:edit, :admin, @category] %>
      </h3>
    </section>
  </aside>
  <aside class="col-md-6">
    <section class="user_info">
      <% @questions.each do |question| %>
        <h2>
          <%= link_to question.content, [:admin, @category, question] %>
          <%= link_to "", [:admin, @category, question], method: :delete,
            data: {confirm: t(".confirm_sure")},
            class: "glyphicon glyphicon-trash" %>
        </h2>
      <% end %>
    </section>
  </aside>
</div>