config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root to: "exams#new", as: "authenticated_root"
  end
  unauthenticated do
    root "static_pages#home"
  end

  devise_for :users

  resources :users, only: :show

  resources :exams, except: [:index, :destroy]
  namespace :admin do
    root "users#index"
    resources :imports, only: :create
    resources :users, except: [:show]
    resources :categories do
      resources :questions
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :exams, dependent: :destroy

  validates :name, presence: true

  def guest?
    id.nil?
  end

  def self.import file
    CSV.foreach file.path, headers: true do |row|
      User.create row.to_hash.merge password:
        Devise.friendly_token.first(8)
    end
  end
end

app/controllers/admin/users_controller.rb
require "csv"
class Admin::UsersController < Admin::BaseController
  load_and_authorize_resource

  def index
    respond_to do |format|
      format.html do
        @search = @users.search params[:q]
        @users = @search.result.page params[:page]
      end
      format.csv do
        send_data render_to_string, type: Settings.user.csv.type,
          filename: Settings.user.csv.filename
      end
    end
  end

  def new
  end

  def create
    if @user.save
      redirect_to @user, success: t("messages.admin.user.created")
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      redirect_to @user, success: t("messages.admin.user.updated")
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_url, success: t("messages.admin.user.deleted")
  end

  private
  def user_params
    params.require(:user).permit :name, :email
  end

  def create_params
    user_params.merge password:
      Devise.friendly_token.first(Settings.user.password_length)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: 80}
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = "#{Settings.gravatar_url}#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control" %>

  <%= f.submit t(".submit"), class: "btn btn-primary" %>
<% end %>

app/views/admin/users/_import_csv_form.html.erb
<%= form_tag admin_imports_path, url: admin_imports_path,
  html: {method: :post}, multipart: true do %>
  <%= file_field_tag :file, class: "form-control" %>
  <%= submit_tag t(".import"), class: "btn btn-primary" %>
<% end %>

app/views/admin/users/_search_form.html.erb
<%= search_form_for @search, url: admin_users_path,
  html: {method: :get} do |f| %>

  <div class="field col-md-6">
    <%= f.label :name_cont, t(".name") %>
    <%= f.text_field :name_cont, class: "form-control" %>
  </div>

  <div class="field col-md-6">
    <%= f.label :email_cont, t(".email") %>
    <%= f.text_field :email_cont, class: "form-control" %>
  </div>

  <div class="field col-md-6">
    <%= f.label :created_at_gteq, t(".created_from") %>
    <%= f.date_field :created_at_gteq, class: "form-control " %>
  </div>
  <div class="field col-md-6">
    <%= f.label :created_at_lteq, t(".to") %>
    <%= f.date_field :created_at_lteq, class: "form-control" %>    
  </div>

  <div class="actions col-md-1">
    <%= f.submit t(".submit"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/users/_user.csv.erb
<%= CSV.generate_line Settings.user.csv.fields.map{|field| user.try field} %>

app/views/admin/users/_user.html.erb
<aside>
  <section class="user_info">
    <h1>
      <%= link_to edit_admin_user_path(user) do %>
        <%= gravatar_for user, size: Settings.user.avatar_size %>
        <%= user.name %>
      <% end %>
      <%= link_to "", admin_user_path(user), method: :delete, data: {confirm: 
        t(".confirm_delete")}, class: "glyphicon glyphicon-trash" %>
    </h1>
  </section>
</aside>

app/views/admin/users/edit.html.erb
<% provide :title, t(".title") %>

<h1><%= t ".title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/users/index.csv.erb
<%= CSV.generate_line Settings.user.csv.fields %>
<%= render @users %>

app/views/admin/users/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>

<h2 class="left">
  <%= t ".search_f" %>
</h2>
<div class="row">
  <%= render "search_form" %>
</div>
<hr>

<h2 class="left">
  <%= t ".import_csv" %>
</h2>
<div class="row">
  <div class="col-md-5">
    <%= render "import_csv_form" %>
    <hr>
  </div>
</div>

<h1 class="left">
  <%= t ".users_list" %>
</h1>
<%= link_to t(".create"), [:new, :admin, :user],
  class: "btn btn-primary" %>
<%= link_to t(".export_csv"), admin_users_path(format: :csv),
  class: "btn btn-primary" %>
<ul class="users">
  <%= render @users %>
</ul>
<%= paginate @users %>

app/views/admin/users/new.html.erb
<% provide :title, t(".title") %>

<h1><%= t ".title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>