config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root to: "exams#new", as: "authenticated_root"
  end
  unauthenticated do
    root "static_pages#home"
  end

  devise_for :users

  resources :users, only: :show

  resources :exams, except: [:index, :destroy]
  namespace :admin do
    root "users#index"
    resources :imports, only: :create
    resources :users, except: [:show]
    resources :categories do
      resources :questions
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p><%= t ".copyright" %></p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to t(".home"), root_path %></li>
          <% if current_user.admin? %>
            <li><%= link_to t(".mana_cate"), admin_categories_path %></li>
            <li><%= link_to t(".mana_user"), admin_users_path %></li>
          <% end %>
          <li id="fat-menu" class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
              <%= current_user.name %> <b class="caret"></b>
            <% end %> 
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".setting"), edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".logout"), destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to t(".signin"), new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>